//! Tab contents and window chrome. Each module adds methods to `ArcticApp`.

mod about;
mod accounts;
mod client_style;
mod dialogs;
mod instances;
mod logs;

pub use instances::{InstancePage, InstancesUi};
pub use logs::LogViewKey;
pub use profiles::ProfileDialog;
mod nav;
mod network;
pub use network::NetworkUi;
mod onboarding;
pub use onboarding::Onboarding;
mod play;
pub(crate) mod play_worlds;
pub use play::VersionView;
mod migrate;
mod profiles;
pub use migrate::MigrateUi;
mod screenshots;
pub use screenshots::ScreenshotsUi;
mod servers;
pub use servers::ServersUi;
mod discover;
pub use discover::DiscoverUi;
mod chat;
pub use chat::ChatUi;
mod friends;
pub use friends::FriendsUi;
mod game_defaults;
pub use game_defaults::DefaultsUi;
mod voice_settings;
pub use voice_settings::VoiceSettingsUi;
mod settings;
mod sharing;
pub use sharing::ShareUi;
mod skins;
mod sponsor;
pub use skins::SkinsUi;
mod together;
pub use together::TogetherUi;
mod shell;
