pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

// Arctic Client for every Fabric version of Minecraft. Build from mod/:
// ./gradlew -p versions/fabric build -Pminecraft_version=26.3
rootProject.name = 'arctic-mod'
