//! Arctic's companion mod (capes from Arctic and the in-game Arctic menu),
//! bundled with the launcher and kept in sync in Fabric and Quilt instances.

use std::fs;
use std::path::Path;

use crate::Result;
use crate::error::IoContext;

/// File name inside an instance's `mods` folder.
pub const FILE_NAME: &str = "arctic-mod.jar";
/// Overrides the cosmetics server the mod talks to (for testing).
pub const COSMETICS_URL_ENV: &str = "ARCTIC_COSMETICS_URL";

// JARS: generated by build.rs from mod/targets.json.
include!(concat!(env!("OUT_DIR"), "/arctic_jars.rs"));

fn jar_for(game_version: &str) -> Option<&'static [u8]> {
    JARS.iter()
        .find(|(v, _)| *v == game_version)
        .map(|(_, jar)| *jar)
}

/// True if the mod exists for this Minecraft version.
pub fn supports(game_version: &str) -> bool {
    jar_for(game_version).is_some()
}

/// Put the mod in `mods_dir` (when enabled and available) or take it out.
pub fn sync(mods_dir: &Path, game_version: &str, enabled: bool) -> Result<()> {
    let path = mods_dir.join(FILE_NAME);
    match jar_for(game_version).filter(|_| enabled) {
        Some(jar) => {
            if fs::read(&path).is_ok_and(|existing| existing == jar) {
                return Ok(());
            }
            fs::create_dir_all(mods_dir).at(mods_dir)?;
            fs::write(&path, jar).at(&path)
        }
        None if path.exists() => fs::remove_file(&path).at(&path),
        None => Ok(()),
    }
}

/// The oldest Fabric Loader the mod for `game` runs on (its
/// `fabric.mod.json` says `"fabricloader": ">=x"`).
pub fn min_loader(game_version: &str) -> Option<String> {
    let jar = jar_for(game_version)?;
    let mut zip = zip::ZipArchive::new(std::io::Cursor::new(jar)).ok()?;
    let mut text = String::new();
    std::io::Read::read_to_string(&mut zip.by_name("fabric.mod.json").ok()?, &mut text).ok()?;
    let json: serde_json::Value = serde_json::from_str(&text).ok()?;
    let range = json.pointer("/depends/fabricloader")?.as_str()?;
    Some(range.trim_start_matches(">=").trim().to_owned())
}

/// Can the mod for `game` run on Fabric Loader `loader_version`?
pub fn loader_fits(game_version: &str, loader_version: &str) -> bool {
    min_loader(game_version).is_none_or(|min| at_least(loader_version, &min))
}

/// `a >= b`, comparing the numbers in the versions (`0.19.10` > `0.19.5`).
pub fn at_least(a: &str, b: &str) -> bool {
    let nums = |s: &str| -> Vec<u64> {
        s.split(|c: char| !c.is_ascii_digit())
            .filter(|p| !p.is_empty())
            .filter_map(|p| p.parse().ok())
            .collect()
    };
    nums(a) >= nums(b)
}

/// Fabric loader version for running the Arctic Client on `game`: the
/// newest stable build, remembered so launches also work offline.
pub fn client_loader(dirs: &crate::storage::DataDirs, game: &str) -> Option<String> {
    let cache = dirs.meta().join("arctic-client-loader.json");
    let mut known: std::collections::HashMap<String, String> = crate::storage::load_json(&cache)
        .ok()
        .flatten()
        .unwrap_or_default();
    let fresh = crate::loaders::loader_versions(crate::loaders::LoaderKind::Fabric, game)
        .ok()
        .and_then(|versions| {
            versions
                .iter()
                .find(|v| v.stable)
                .or(versions.first())
                .map(|v| v.id.clone())
        });
    match fresh {
        Some(version) => {
            if known.get(game) != Some(&version) {
                known.insert(game.to_owned(), version.clone());
                let _ = crate::storage::save_json(&cache, &known);
            }
            Some(version)
        }
        None => known.get(game).cloned(),
    }
}

/// JVM flag pointing the mod at a different cosmetics server, if set.
pub fn jvm_flag() -> Option<String> {
    std::env::var(COSMETICS_URL_ENV)
        .ok()
        .filter(|url| url.starts_with("http://") || url.starts_with("https://"))
        .map(|url| format!("-Darctic.cosmetics.url={url}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn installs_updates_and_removes() {
        let dir = tempfile::tempdir().unwrap();
        let mods = dir.path().join("mods");
        sync(&mods, "26.3", true).unwrap();
        let path = mods.join(FILE_NAME);
        assert!(path.exists());
        fs::write(&path, b"old").unwrap();
        sync(&mods, "26.3", true).unwrap();
        assert_ne!(fs::read(&path).unwrap(), b"old");
        sync(&mods, "26.3", false).unwrap();
        assert!(!path.exists());
        // Unsupported versions never get it.
        sync(&mods, "1.8.9", true).unwrap();
        assert!(!path.exists());
    }

    #[test]
    fn one_jar_serves_every_patch_it_covers() {
        assert!(supports("26.1"));
        assert_eq!(jar_for("26.1"), jar_for("26.1.2"));
        assert_ne!(jar_for("26.2"), jar_for("26.3"));
    }

    #[test]
    fn bundled_jar_is_a_fabric_mod() {
        let jar = jar_for("26.3").unwrap();
        let mut zip = zip::ZipArchive::new(std::io::Cursor::new(jar)).unwrap();
        assert!(zip.by_name("fabric.mod.json").is_ok());
    }
}
