//! Arctic's companion mod (capes from Arctic and the in-game Arctic menu),
//! bundled with the launcher and kept in sync in Fabric and Quilt instances.

use std::collections::HashMap;
use std::fs;
use std::io::{Cursor, Write};
use std::path::Path;
use std::sync::{Arc, Mutex, OnceLock};

use crate::Result;
use crate::error::IoContext;

/// File name inside an instance's `mods` folder.
pub const FILE_NAME: &str = "arctic-mod.jar";
/// Overrides the cosmetics server the mod talks to (for testing).
pub const COSMETICS_URL_ENV: &str = "ARCTIC_COSMETICS_URL";

// COVERS and PACK: generated by build.rs from mod/targets.json and
// mod/dist/arctic-client.pack.
include!(concat!(env!("OUT_DIR"), "/arctic_jars.rs"));

/// The build target that serves `game_version`.
fn build_for(game_version: &str) -> Option<&'static str> {
    COVERS
        .iter()
        .find(|(v, _)| *v == game_version)
        .map(|(_, build)| *build)
}

/// True if the mod exists for this Minecraft version.
pub fn supports(game_version: &str) -> bool {
    build_for(game_version).is_some()
}

/// The unpacked pack: every jar's file list, and the files (each stored once).
struct Pack {
    /// Build target -> (entry name, file number; `None` for a folder).
    jars: HashMap<String, Vec<(String, Option<usize>)>>,
    data: Vec<u8>,
    /// Where each file starts in `data`, and its size.
    files: Vec<(usize, usize)>,
}

impl Pack {
    const MAGIC: &'static [u8] = b"ARCTICPACK1\n";

    fn unpack(packed: &[u8]) -> Option<Self> {
        let mut raw = Vec::new();
        lzma_rs::lzma_decompress(&mut Cursor::new(packed), &mut raw).ok()?;
        let rest = raw.strip_prefix(Self::MAGIC)?;
        let len = u32::from_le_bytes(rest.get(..4)?.try_into().ok()?) as usize;
        #[derive(serde::Deserialize)]
        struct Index {
            jars: HashMap<String, Vec<(String, i64)>>,
            sizes: Vec<usize>,
        }
        let index: Index = serde_json::from_slice(rest.get(4..4 + len)?).ok()?;
        let start = Self::MAGIC.len() + 4 + len;
        let mut files = Vec::with_capacity(index.sizes.len());
        let mut at = start;
        for size in index.sizes {
            files.push((at, size));
            at += size;
        }
        if at > raw.len() {
            return None;
        }
        let jars = index
            .jars
            .into_iter()
            .map(|(build, entries)| {
                let entries = entries
                    .into_iter()
                    .map(|(name, file)| (name, usize::try_from(file).ok()))
                    .collect();
                (build, entries)
            })
            .collect();
        Some(Self {
            jars,
            data: raw,
            files,
        })
    }

    fn file(&self, number: usize) -> Option<&[u8]> {
        let (at, size) = *self.files.get(number)?;
        self.data.get(at..at + size)
    }

    /// The jar, rebuilt the same way every time (so an unchanged one in an
    /// instance is left alone).
    fn jar(&self, build: &str) -> Option<Vec<u8>> {
        let entries = self.jars.get(build)?;
        let mut zip = zip::ZipWriter::new(Cursor::new(Vec::new()));
        let options = zip::write::SimpleFileOptions::default()
            .compression_method(zip::CompressionMethod::Deflated)
            .last_modified_time(zip::DateTime::default());
        for (name, file) in entries {
            match file {
                None => zip.add_directory(name.as_str(), options).ok()?,
                Some(n) => {
                    zip.start_file(name.as_str(), options).ok()?;
                    zip.write_all(self.file(*n)?).ok()?;
                }
            }
        }
        Some(zip.finish().ok()?.into_inner())
    }
}

/// Unpacked on first use (a fraction of a second), then kept.
fn pack() -> Option<&'static Pack> {
    static PACKED: OnceLock<Option<Pack>> = OnceLock::new();
    PACKED
        .get_or_init(|| {
            if let Some(dev) = dev_pack() {
                return Some(dev);
            }
            let pack = Pack::unpack(PACK);
            if pack.is_none() && !PACK.is_empty() {
                log::error!("the bundled Arctic Client is damaged");
            }
            pack
        })
        .as_ref()
}

/// A hash of the developer pack in use, so its jars replace ones from
/// another pack (they'd otherwise pass for current: see [`pack_id`]).
static DEV_PACK_ID: OnceLock<u64> = OnceLock::new();

/// Which pack the jars come from: the bundled one, or a developer pack.
fn pack_id() -> u64 {
    if option_env!("ARCTIC_DEV_PACK").is_some() {
        let _ = pack();
        if let Some(id) = DEV_PACK_ID.get() {
            return *id;
        }
    }
    PACK_ID
}

/// Developer builds (made with `ARCTIC_DEV_PACK=1`) use an `arctic-client.pack`
/// next to the launcher when there is one, so a change to the mod needs only
/// `python mod/build.py`, not a launcher rebuild. Release builds never do.
fn dev_pack() -> Option<Pack> {
    option_env!("ARCTIC_DEV_PACK")?;
    let path = std::env::current_exe()
        .ok()?
        .with_file_name("arctic-client.pack");
    let bytes = fs::read(&path).ok()?;
    let pack = Pack::unpack(&bytes);
    if pack.is_some() {
        let mut hasher = std::hash::DefaultHasher::new();
        std::hash::Hasher::write(&mut hasher, &bytes);
        let _ = DEV_PACK_ID.set(std::hash::Hasher::finish(&hasher));
    }
    match &pack {
        Some(_) => log::info!("using the Arctic Client from {}", path.display()),
        None => log::warn!(
            "{} is damaged; using the bundled Arctic Client",
            path.display()
        ),
    }
    pack
}

/// Jars rebuilt so far, by build target.
type JarCache = Mutex<HashMap<&'static str, Arc<Vec<u8>>>>;

/// The mod's jar for `game_version` (built once per target).
fn jar_for(game_version: &str) -> Option<Arc<Vec<u8>>> {
    static JARS: OnceLock<JarCache> = OnceLock::new();
    let build = build_for(game_version)?;
    let mut jars = JARS.get_or_init(Default::default).lock().ok()?;
    if let Some(jar) = jars.get(build) {
        return Some(jar.clone());
    }
    let jar = Arc::new(pack()?.jar(build)?);
    jars.insert(build, jar.clone());
    Some(jar)
}

/// Next to the jar: which pack and target it came from, and its size, so a
/// current jar is recognized without unpacking anything.
const STAMP_NAME: &str = ".arctic-mod.stamp";

/// Put the mod in `mods_dir` (when enabled and available) or take it out.
pub fn sync(mods_dir: &Path, game_version: &str, enabled: bool) -> Result<()> {
    let path = mods_dir.join(FILE_NAME);
    let stamp_path = mods_dir.join(STAMP_NAME);
    let Some(build) = build_for(game_version).filter(|_| enabled) else {
        let _ = fs::remove_file(&stamp_path);
        return match path.exists() {
            true => fs::remove_file(&path).at(&path),
            false => Ok(()),
        };
    };
    let id = pack_id();
    let stamp = |len: u64| format!("{id:016x} {build} {len}");
    if let Ok(meta) = fs::metadata(&path)
        && fs::read_to_string(&stamp_path).is_ok_and(|s| s == stamp(meta.len()))
    {
        return Ok(());
    }
    let Some(jar) = jar_for(game_version) else {
        return Ok(());
    };
    fs::create_dir_all(mods_dir).at(mods_dir)?;
    fs::write(&path, jar.as_slice()).at(&path)?;
    fs::write(&stamp_path, stamp(jar.len() as u64)).at(&stamp_path)
}

/// The oldest Fabric Loader the mod for `game` runs on (its
/// `fabric.mod.json` says `"fabricloader": ">=x"`).
pub fn min_loader(game_version: &str) -> Option<String> {
    let build = build_for(game_version)?;
    MIN_LOADER
        .iter()
        .find(|(b, _)| *b == build)
        .map(|(_, loader)| (*loader).to_owned())
}

/// Can the mod for `game` run on Fabric Loader `loader_version`?
pub fn loader_fits(game_version: &str, loader_version: &str) -> bool {
    min_loader(game_version).is_none_or(|min| at_least(loader_version, &min))
}

/// `a >= b`, comparing the numbers in the versions (`0.19.10` > `0.19.5`).
pub fn at_least(a: &str, b: &str) -> bool {
    let nums = |s: &str| -> Vec<u64> {
        s.split(|c: char| !c.is_ascii_digit())
            .filter(|p| !p.is_empty())
            .filter_map(|p| p.parse().ok())
            .collect()
    };
    nums(a) >= nums(b)
}

/// How long a looked-up Fabric Loader version is used before asking again.
const LOADER_RECHECK: std::time::Duration = std::time::Duration::from_secs(6 * 60 * 60);

/// Fabric loader version for running the Arctic Client on `game`: the
/// newest stable build, remembered so launches also work offline.
pub fn client_loader(dirs: &crate::storage::DataDirs, game: &str) -> Option<String> {
    let cache = dirs.meta().join("arctic-client-loader.json");
    let mut known: std::collections::HashMap<String, String> = crate::storage::load_json(&cache)
        .ok()
        .flatten()
        .unwrap_or_default();
    // Asked recently: don't hold up the launch with another round trip.
    let recent = std::fs::metadata(&cache)
        .and_then(|m| m.modified())
        .ok()
        .and_then(|t| t.elapsed().ok())
        .is_some_and(|age| age < LOADER_RECHECK);
    if recent && let Some(version) = known.get(game) {
        return Some(version.clone());
    }
    let fresh = crate::loaders::loader_versions(crate::loaders::LoaderKind::Fabric, game)
        .ok()
        .and_then(|versions| {
            versions
                .iter()
                .find(|v| v.stable)
                .or(versions.first())
                .map(|v| v.id.clone())
        });
    match fresh {
        Some(version) => {
            known.insert(game.to_owned(), version.clone());
            // Saved every time: the file's age says when we last asked.
            let _ = crate::storage::save_json(&cache, &known);
            Some(version)
        }
        None => known.get(game).cloned(),
    }
}

/// JVM flag pointing the mod at a different cosmetics server, if set.
pub fn jvm_flag() -> Option<String> {
    std::env::var(COSMETICS_URL_ENV)
        .ok()
        .filter(|url| url.starts_with("http://") || url.starts_with("https://"))
        .map(|url| format!("-Darctic.cosmetics.url={url}"))
}

#[cfg(test)]
mod tests {
    use std::io::Read;

    use super::*;

    #[test]
    fn installs_updates_and_removes() {
        let dir = tempfile::tempdir().unwrap();
        let mods = dir.path().join("mods");
        sync(&mods, "26.3", true).unwrap();
        let path = mods.join(FILE_NAME);
        assert!(path.exists());
        // Current and stamped: left alone, without unpacking anything.
        let written = fs::metadata(&path).unwrap().modified().unwrap();
        sync(&mods, "26.3", true).unwrap();
        assert_eq!(fs::metadata(&path).unwrap().modified().unwrap(), written);
        // Changed by someone else: put back.
        fs::write(&path, b"old").unwrap();
        sync(&mods, "26.3", true).unwrap();
        assert_ne!(fs::read(&path).unwrap(), b"old");
        sync(&mods, "26.3", false).unwrap();
        assert!(!path.exists());
        // Unsupported versions never get it.
        sync(&mods, "1.7.10", true).unwrap();
        assert!(!path.exists());
    }

    #[test]
    fn one_jar_serves_every_patch_it_covers() {
        assert!(supports("26.1"));
        assert_eq!(jar_for("26.1"), jar_for("26.1.2"));
        assert_ne!(jar_for("26.2"), jar_for("26.3"));
    }

    #[test]
    fn bundled_jar_is_a_fabric_mod() {
        let jar = jar_for("26.3").unwrap();
        let mut zip = zip::ZipArchive::new(Cursor::new(jar.as_slice())).unwrap();
        assert!(zip.by_name("fabric.mod.json").is_ok());
        assert!(min_loader("26.3").is_some());
    }

    #[test]
    fn a_rebuilt_jar_is_the_same_every_time() {
        let pack = pack().unwrap();
        assert_eq!(pack.jar("1.8.9"), pack.jar("1.8.9"));
    }

    #[test]
    fn rebuilt_jars_hold_what_the_built_ones_do() {
        // Only where the jars were built here (they aren't committed).
        let dist = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../mod/dist");
        for (_, build) in COVERS {
            let Ok(built) = fs::read(dist.join(format!("arctic-mod-{build}.jar"))) else {
                continue;
            };
            let mut built = zip::ZipArchive::new(Cursor::new(built)).unwrap();
            let rebuilt = pack().unwrap().jar(build).unwrap();
            let mut rebuilt = zip::ZipArchive::new(Cursor::new(rebuilt)).unwrap();
            assert_eq!(built.len(), rebuilt.len(), "{build}");
            for i in 0..built.len() {
                let mut a = built.by_index(i).unwrap();
                let name = a.name().to_owned();
                let mut want = Vec::new();
                a.read_to_end(&mut want).unwrap();
                let mut got = Vec::new();
                rebuilt
                    .by_name(&name)
                    .unwrap()
                    .read_to_end(&mut got)
                    .unwrap();
                assert!(want == got, "{build}: {name} differs");
            }
        }
    }
}
