[package]
name = "arctic-cli"
description = "Arctic Launcher command line interface (headless)."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]
arctic-core = { version = "0.1.0", path = "../arctic-core" }
clap = { version = "4.6.7", features = ["derive", "env"] }
log = "0.4.34"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

[[bin]]
name = "arctic"
path = "src/main.rs"
